name: CADCData Docker Image builds

on:
  pull_request:
  push:
  release:

jobs:

  build-3_13:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: cadcdata
      version: '3.13'
      flavour: slim

  build-3_12:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: cadcdata
      version: '3.12'
      flavour: slim

  build-3_11:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: cadcdata
      version: '3.11'
      flavour: slim
